// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rAqfWhCkGP4j2Cb15hG-Y6FHaIY-cW4',
    appId: '1:193096512309:web:1b51ad9afd956f0876927c',
    messagingSenderId: '193096512309',
    projectId: 'kasvihuonesovellus',
    authDomain: 'kasvihuonesovellus.firebaseapp.com',
    storageBucket: 'kasvihuonesovellus.appspot.com',
    measurementId: 'G-7TEK6Y7L1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsFd95LnlBVC4XzbE1oVXtYYFk5WA9rI',
    appId: '1:193096512309:android:1d461bb96d2d496276927c',
    messagingSenderId: '193096512309',
    projectId: 'kasvihuonesovellus',
    storageBucket: 'kasvihuonesovellus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCTYsM2_IRErp6kVvEhmudOVjWSfbY8s',
    appId: '1:193096512309:ios:a65caf52168bfb7776927c',
    messagingSenderId: '193096512309',
    projectId: 'kasvihuonesovellus',
    storageBucket: 'kasvihuonesovellus.appspot.com',
    iosBundleId: 'com.example.kasvihuonesovellus',
  );
}
